version: '3'
services:
    mongo:
        image: mongo:4.4.6
        container_name: 'mongo'
        command: mongod
        environment:
            - DATABASE_NAME=template
        restart: always
        ports:
            - '27017:27017'
    emqx:
        container_name: emqx
        image: emqx:4.3.5
        restart: always
        ports:
            [
                '1883:1883',
                '8081:8081',
                '8083:8083',
                '8084:8084',
                '8883:8883',
                '11883:11883',
                '18083:18083',
                '4369:4369',
                '4370:4370',
                '5369:5369',
                '6369:6369',
                '6370:6370'
            ]
    
